<a href="https://colab.research.google.com/github/ridhoaryo/intro-to-pytorch/blob/main/Intro_to_Torch_20250224.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.3.0
aiohappyeyeballs                   2.4.6
aiohttp                            3.11.12
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.23
albumentations                     2.0.4
ale-py                             0.10.2
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
astropy                            7.0.1
astropy-iers-data                  0.2025.2.17.0.34.13
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread          

# Tensor



*   A torch.Tensor is multi-dimensional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's)
* Default data type float32.
* More suitable for deep learning than a numpy array.



In [2]:
import torch
import numpy as np

# Lists

In [3]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [4]:
my_list2 = [[1,2,3,4,5], [6,7,8,9,10]]
print(my_list2)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


# Numpy

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.95339728, 0.09255267, 0.60594319, 0.66000067],
       [0.12098317, 0.79257147, 0.15162433, 0.07863426],
       [0.18842437, 0.61928665, 0.15032701, 0.15764179]])

In [6]:
np1.dtype

dtype('float64')

# Tensors

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.5894, -0.2742, -0.4169, -0.8449],
        [-0.4937, -1.5043,  0.3415, -0.3453],
        [-1.9655,  1.5687,  0.6467, -0.9714]])

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor ot of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9534, 0.0926, 0.6059, 0.6600],
        [0.1210, 0.7926, 0.1516, 0.0786],
        [0.1884, 0.6193, 0.1503, 0.1576]], dtype=torch.float64)

# Going deep..


In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
## Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2.reshape(2,-1) # always the factor of the length of the array.

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [19]:
# when you are using reshape, whenever you update the original array, the copy will be also updated
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [20]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch7[7]

tensor(7)

In [22]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [24]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

# Tensor Math Operations
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and Longhand
* Reassignment

In [25]:
tensora = torch.tensor([1,2,3,4])
tensorb = torch.tensor([5,6,7,8])

In [26]:
# addition
tensora + tensorb

tensor([ 6,  8, 10, 12])

In [27]:
# addition longhand
torch.add(tensora, tensorb)

tensor([ 6,  8, 10, 12])

In [28]:
# substraction
tensorb - tensora

tensor([4, 4, 4, 4])

In [29]:
# substraction longhand
torch.sub(tensorb, tensora)

tensor([4, 4, 4, 4])

In [30]:
# multiplication
tensora * tensorb

tensor([ 5, 12, 21, 32])

In [31]:
# multiplication longhand
torch.mul(tensora, tensorb)

tensor([ 5, 12, 21, 32])

In [32]:
# division
tensorb/tensora

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
# division longhand
torch.div(tensorb, tensora)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [34]:
# reminder
tensorb % tensora

tensor([0, 0, 1, 0])

In [35]:
# reminder longhand
torch.remainder(tensorb, tensora)

tensor([0, 0, 1, 0])

In [36]:
# power / exponents
tensora**tensorb

tensor([    1,    64,  2187, 65536])

In [37]:
# power longhand
torch.pow(tensora, tensorb)

tensor([    1,    64,  2187, 65536])

In [38]:
# reassignment (add "_")
tensora.add_(tensorb)

tensor([ 6,  8, 10, 12])

In [39]:
tensora

tensor([ 6,  8, 10, 12])